version: "3"

services:
  api:
    container_name: part7
    build: ./app
    tty: true
    volumes:
      - ./app:/usr/src/app
    ports:
      - 5000:5000
    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy
    command: python3 main.py

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_database
    volumes:
      - ./db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/mysql/init:/docker-entrypoint-initdb.d # sqlの初期化を実行する
    ports:
      - 3306:3306
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 1s
      retries: 120

  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_database
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./db/postgres/init:/docker-entrypoint-initdb.d # sqlの初期化を実行する
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5